### ISSUE TITLE
running predictor for specific boxes

### ISSUE THREAD

**Issue by wolet** [ruotianluo/pytorch-faster-rcnn#10]
Hello,

Is it possible to run the fRCNN for specific boxes (e.g. hand drawn) without using RPN? if so, do you have any pointers for where to start doing that?

thanks in advance!

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/pytorch-faster-rcnn/blob/master/lib/nets/network.py#L352
replace this line with something else. The format of roi is (x1,y1,x2,y2) (x is along horizontal, y is along vertical.)

**Comment by wolet** [comment]
thanks it works!
