### ISSUE TITLE
How to use this code without GPU

### ISSUE THREAD

**Issue by smallnine9** [ruotianluo/pytorch-faster-rcnn#100]
in make.sh . I find `nvcc -c -o roi_pooling_kernel.cu.o roi_pooling_kernel.cu -x cu -Xcompiler -fPIC $CUDA_ARCH `, but without cuda , it can not find nvcc, how to solve it?

**Comment by nick-jia** [comment]
This can be solved by installing cuda (installing cuda does not require existence of GPU).
Before setting up, go to line 270 of config.py, set `__C.USE_GPU_NMS = False` .
