### ISSUE TITLE
Memory leak issue of ROI pooling layer

### ISSUE THREAD

**Issue by Wanger-SJTU** [ruotianluo/pytorch-faster-rcnn#118]
I used the ROI pooling layer only, but during the training process, the usuage of GPU memory is growing until OOM.

the `nvidia-smi` output
iter 10(appro)
+---------------------------------+------------------------+--------------------+
|   2  GeForce GTX 108...  Off      | 00000000:0A:00.0 Off   |                      N/A  |
|  0%   57C    P2   213W / 250W |   4889MiB / 11178MiB |     48%      Default |
iter 20(appro)
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off      |  00000000:0A:00.0 Off  |                      N/A |
|  0%   63C    P2   234W / 250W |   5489MiB / 11178MiB |     89%      Default |
+-------------------------------+----------------------+----------------------+
iter 40(appro)
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 33%   62C    P2    66W / 250W |   5617MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
iter 60(appro)
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off      | 00000000:0A:00.0 Off       |                  N/A |
| 38%   64C    P2    81W / 250W |   6769MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

the Input image size is 1024*2048（RGB）, conv_feats fed into roi pooling is 1*256*128*256， rois_info is prepared before training, 400-900 for each image. 

>2018-11-15 17:12:02,279 INFO Visdom successfully connected to server
loaded epoch-17-step-278000.pth
Region_Net[0]: loss:1.73549  acc:0.37500:   7%| | 223/2975 [06:12<1:16:37,  1.67s/it]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "transfer_train.py", line 90, in <module>
    main()
  File "transfer_train.py", line 85, in main
    train_transfer(opt)
  File "transfer_train.py", line 68, in train_transfer
    RegionNet_solver.train(region_dataset)
  File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/SolverRegionNet.py", line 106, in train
    acc_list = self.train_epoch(dataLoader, epoch, acc_list)
  File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/SolverRegionNet.py", line 81, in train_epoch
    loss, acc = self.Region_model.build_loss(img, rois[0], lbls[0])
  File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/RegionNet.py", line 89, in build_loss
    pooled_flat = self.head_to_tail(pooled)
  File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/RegionNet.py", line 66, in head_to_tail
    fc = self.feats.layer4(pool5).mean(3).mean(2)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/extractors.py", line 98, in forward
    out = self.bn2(out)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu:58

**Comment by chengxianda54321** [comment]
您好，我也出现了CUDA out of memory的问题，请问您解决了吗？

**Comment by chengxianda54321** [comment]
> I used the ROI pooling layer only, but during the training process, the usuage of GPU memory is growing until OOM.
> 
> the `nvidia-smi` output
> iter 10(appro)
> +---------------------------------+------------------------+--------------------+
> | 2 GeForce GTX 108... Off | 00000000:0A:00.0 Off | N/A |
> | 0% 57C P2 213W / 250W | 4889MiB / 11178MiB | 48% Default |
> iter 20(appro)
> +-------------------------------+----------------------+----------------------+
> | 2 GeForce GTX 108... Off | 00000000:0A:00.0 Off | N/A |
> | 0% 63C P2 234W / 250W | 5489MiB / 11178MiB | 89% Default |
> +-------------------------------+----------------------+----------------------+
> iter 40(appro)
> +-------------------------------+----------------------+----------------------+
> | 2 GeForce GTX 108... Off | 00000000:0A:00.0 Off | N/A |
> | 33% 62C P2 66W / 250W | 5617MiB / 11178MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> iter 60(appro)
> +-------------------------------+----------------------+----------------------+
> | 2 GeForce GTX 108... Off | 00000000:0A:00.0 Off | N/A |
> | 38% 64C P2 81W / 250W | 6769MiB / 11178MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> 
> the Input image size is 1024_2048（RGB）, conv_feats fed into roi pooling is 1_256_128_256， rois_info is prepared before training, 400-900 for each image.
> 
> > 2018-11-15 17:12:02,279 INFO Visdom successfully connected to server
> > loaded epoch-17-step-278000.pth
> > Region_Net[0]: loss:1.73549  acc:0.37500:   7%| | 223/2975 [06:12<1:16:37,  1.67s/it]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
> > Traceback (most recent call last):
> > File "transfer_train.py", line 90, in 
> > main()
> > File "transfer_train.py", line 85, in main
> > train_transfer(opt)
> > File "transfer_train.py", line 68, in train_transfer
> > RegionNet_solver.train(region_dataset)
> > File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/SolverRegionNet.py", line 106, in train
> > acc_list = self.train_epoch(dataLoader, epoch, acc_list)
> > File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/SolverRegionNet.py", line 81, in train_epoch
> > loss, acc = self.Region_model.build_loss(img, rois[0], lbls[0])
> > File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/RegionNet.py", line 89, in build_loss
> > pooled_flat = self.head_to_tail(pooled)
> > File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/RegionNet.py", line 66, in head_to_tail
> > fc = self.feats.layer4(pool5).mean(3).mean(2)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
> > input = module(input)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/media/sjtu/831bebd9-c866-4ece-b878-5dbd68e5ca50/sjtu/CH/seg_trans_2018_9_26/models/extractors.py", line 98, in forward
> > out = self.bn2(out)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> > result = self.forward(*input, **kwargs)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
> > self.training or not self.track_running_stats, self.momentum, self.eps)
> > File "/home/sjtu/anaconda2/envs/FCN/lib/python3.5/site-packages/torch/nn/functional.py", line 1194, in batch_norm
> > training, momentum, eps, torch.backends.cudnn.enabled
> > RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu:58

您解决了吗
