### ISSUE TITLE
ImportError: No module named google.protobuf Command exited with non-zero status 1

### ISSUE THREAD

**Issue by vinodkkurmi** [ruotianluo/pytorch-faster-rcnn#12]
I facing the problem while training the model. 

ImportError: No module named google.protobuf
Command exited with non-zero status 1
When I try to install protobuf I got 
pip install protobuf
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages

**Comment by ruotianluo** [comment]
Can you provide full trace.

**Comment by vinodkkurmi** [comment]
This is the full trace 
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=1
+ DATASET=pascal_voc
+ NET=vgg16
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case ${DATASET} in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ STEPSIZE='[50000]'
+ ITERS=70000
+ ANCHORS='[8,16,32]'
+ RATIOS='[0.5,1,2]'
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-09-17_23-58-58
+ exec
++ tee -a experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-09-17_23-58-58
+ echo Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-09-17_23-58-58
Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2017-09-17_23-58-58
+ set +x
+ '[' '!' -f output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_70000.pth.index ']'
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=1
+ time python ./tools/trainval_net.py --weight data/imagenet_weights/vgg16.pth --imdb voc_2007_trainval --imdbval voc_2007_test --iters 70000 --cfg experiments/cfgs/vgg16.yml --net vgg16 --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]' TRAIN.STEPSIZE '[50000]'
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 11, in <module>
    from model.train_val import get_training_roidb, train_net
  File "/users/gpu/vinod1/code_detection/pytorch/state_ot_art_code/pytorch-faster-rcnn-master/tools/../lib/model/train_val.py", line 10, in <module>
    import tensorboardX as tb
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/writer.py", line 24, in <module>
    from .src import event_pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/src/event_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
Command exited with non-zero status 1
0.09user 0.60system 0:00.08elapsed 849%CPU (0avgtext+0avgdata 19268maxresident)k
0inputs+0outputs (0major+4777minor)pagefaults 0swaps

**Comment by ruotianluo** [comment]
Did you install tensorflow or tensorflow-tensorboard?

**Comment by ruotianluo** [comment]
Try `conda install protobuf`

**Comment by vinodkkurmi** [comment]
Yes I have install tensorflow ..

**Comment by vinodkkurmi** [comment]
Is this problem related with Tensorflow ??  I am new in python so not fully aware of protobuf stuff. 
I didn't  use the anaconda environment, I use pip 
Thanks for your quick response :)

**Comment by ruotianluo** [comment]
Try google the solution. It may be just the problem of protobuf.
