### ISSUE TITLE
torch.utils.ffi is deprecated

### ISSUE THREAD

**Issue by StrangeTcy** [ruotianluo/pytorch-faster-rcnn#123]
Trying to run `./make.sh` calls on `python build.py` in line 14, which has `from torch.utils.ffi import create_extension` in line 3. Which causes the following error:
>ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Could you update your code to use cpp extensions instead?

**Comment by ruotianluo** [comment]
@adityaarun1

**Comment by adityaarun1** [comment]
@StrangeTcy You are required to run `python setup.py build develop` inside the `lib` directory as mentioned [here](https://github.com/ruotianluo/pytorch-faster-rcnn#installation). `./make.sh` is required if you wish to compile with PyTorch 0.4.0. In that case, please ensure that you checkout from the correct branch.

**Comment by adityaarun1** [comment]
@ruotianluo Do you think a code clean-up for the `1.0` branch will be helpful? I have earlier simply added the required changes, and did not remove obsolete code which was needed for `0.4.0`. I will be happy to remove these if you feel so.

**Comment by ruotianluo** [comment]
0.4 version is already archived in a separate branch. Feel free to submit a pull request.

**Comment by StrangeTcy** [comment]
Ok, seems to be my bad. I'll try to follow your advice and hopefully close the issue.

**Comment by StrangeTcy** [comment]
Yes, it was my bad; once you choose the correct branch, everything seems to work.

**Comment by fengchiyiya** [comment]
damn
