### ISSUE TITLE
a soultion to KeyError:'resnet.bn1.num_batches_tracked'

### ISSUE THREAD

**Issue by Owen-Fish** [ruotianluo/pytorch-faster-rcnn#140]
Nowadys, when i implement the code to train my own data. Using the command:)
**NOTE:I USE THE PRETRAINED_WEIGHTS RESNET101 FOR MY NEW TRAINING**
./train_faster_rcnn.sh 0 pascal_voc res101
but an problem happens that is 'KeyError:'resnet.bn1.num_batches_tracked''.
I went into deeper,  and find this problem occurs when load the pretrained_model.
In lib/model/train_val.py  line 'self.net.load_pretrained_cnn(torch.load(self.pretrained_model))'
before go into this line: self.net is the faster_rcnn structure, but when i debug into 'self.net.load_pretrained_cnn'function, when i look up the structure it became the normal resnet101 network. at that situation, the code will throw KeyError. So i simple move the 'load_pretrained_cnn' from resnet to train_val.py. more details are shown in blow.
![@FX$_RQBPQ~ML~K1($AG68A](https://user-images.githubusercontent.com/39903624/57347842-4d6c2480-7186-11e9-86dd-7277332f07fe.png)
![FLNPZ29}J@PQBDQG5MUP VF](https://user-images.githubusercontent.com/39903624/57347843-4d6c2480-7186-11e9-8bb3-5e5e740302fc.png)

after doing that. my test will run as normal.

**Comment by yongyixiao** [comment]
after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it

**Comment by Owen-Fish** [comment]
> after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it

can you post the screenshot of the error？

**Comment by yongyixiao** [comment]
> > after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it
> 
> can you post the screenshot of the error？

![image](https://user-images.githubusercontent.com/33975438/57519249-683cc580-734d-11e9-8d9f-90558981f97b.png)

**Comment by Owen-Fish** [comment]
> > > after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it
> > 
> > 
> > can you post the screenshot of the error？
> 
> ![image](https://user-images.githubusercontent.com/33975438/57519249-683cc580-734d-11e9-8d9f-90558981f97b.png)

have you ever change this:
![image](https://user-images.githubusercontent.com/39903624/57520213-ae932400-734f-11e9-8017-d1278764cf49.png)

**Comment by Owen-Fish** [comment]
> > > after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it
> > 
> > 
> > can you post the screenshot of the error？
> 
> ![image](https://user-images.githubusercontent.com/33975438/57519249-683cc580-734d-11e9-8d9f-90558981f97b.png)

ok ! you can change the function  in lib/nets/network.py  ---def load_pretrained_cnn()
![image](https://user-images.githubusercontent.com/39903624/57520374-15b0d880-7350-11e9-8fb4-76214a5e7c7c.png)

**Comment by yongyixiao** [comment]
i add  load_pretrained_cnn（） in lib/model/train_val.py



------------------ 原始邮件 ------------------
发件人: "Owen-Fish"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 晚上6:19
收件人: "ruotianluo/pytorch-faster-rcnn"<pytorch-faster-rcnn@noreply.github.com>;
抄送: "Ｍvp_FerryMan"<810700982@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140)



   
after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it
  
can you post the screenshot of the error？
  

  
ok ! you can change the function  in lib/nets/network.py  ---def load_pretrained_cnn()

**Comment by Owen-Fish** [comment]
> i add load_pretrained_cnn（） in lib/model/train_val.py
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"<notifications@github.com>; 发送时间: 2019年5月10日(星期五) 晚上6:19 收件人: "ruotianluo/pytorch-faster-rcnn"<pytorch-faster-rcnn@noreply.github.com>; 抄送: "Ｍvp_FerryMan"<810700982@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it can you post the screenshot of the error？ ok ! you can change the function in lib/nets/network.py ---def load_pretrained_cnn() — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

are you using the resnet for your training? if not i recommmand you to obey the README to complie your code. but if you are using resnet that modification will be alright

**Comment by yongyixiao** [comment]
i just follow the README(ruotianluo/pytorch-faster-rcnn)  step by step。i use the res101 for training,but got the problem,  the use the vgg16, also got the same problem. I try to repress the steps to compile the code. Thank you for your advice



------------------ 原始邮件 ------------------
发件人: "Owen-Fish"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 晚上6:27
收件人: "ruotianluo/pytorch-faster-rcnn"<pytorch-faster-rcnn@noreply.github.com>;
抄送: "Ｍvp_FerryMan"<810700982@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140)



 
i add load_pretrained_cnn（） in lib/model/train_val.py
 …
 ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"notifications@github.com; 发送时间: 2019年5月10日(星期五) 晚上6:19 收件人: "ruotianluo/pytorch-faster-rcnn"pytorch-faster-rcnn@noreply.github.com; 抄送: "Ｍvp_FerryMan"810700982@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it can you post the screenshot of the error？ ok ! you can change the function in lib/nets/network.py ---def load_pretrained_cnn() — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
are you using the resnet for your training? if not i recommmand you to obey the README to complie your code. but if you are using resnet that modification will be alright

**Comment by Owen-Fish** [comment]
> i just follow the README(ruotianluo/pytorch-faster-rcnn) step by step。i use the res101 for training,but got the problem, the use the vgg16, also got the same problem. I try to repress the steps to compile the code. Thank you for your advice
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"<notifications@github.com>; 发送时间: 2019年5月10日(星期五) 晚上6:27 收件人: "ruotianluo/pytorch-faster-rcnn"<pytorch-faster-rcnn@noreply.github.com>; 抄送: "Ｍvp_FerryMan"<810700982@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) i add load_pretrained_cnn（） in lib/model/train_val.py … ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"notifications@github.com; 发送时间: 2019年5月10日(星期五) 晚上6:19 收件人: "ruotianluo/pytorch-faster-rcnn"pytorch-faster-rcnn@noreply.github.com; 抄送: "Ｍvp_FerryMan"810700982@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it can you post the screenshot of the error？ ok ! you can change the function in lib/nets/network.py ---def load_pretrained_cnn() — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. are you using the resnet for your training? if not i recommmand you to obey the README to complie your code. but if you are using resnet that modification will be alright — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.



> i just follow the README(ruotianluo/pytorch-faster-rcnn) step by step。i use the res101 for training,but got the problem, the use the vgg16, also got the same problem. I try to repress the steps to compile the code. Thank you for your advice
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"<notifications@github.com>; 发送时间: 2019年5月10日(星期五) 晚上6:27 收件人: "ruotianluo/pytorch-faster-rcnn"<pytorch-faster-rcnn@noreply.github.com>; 抄送: "Ｍvp_FerryMan"<810700982@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) i add load_pretrained_cnn（） in lib/model/train_val.py … ------------------ 原始邮件 ------------------ 发件人: "Owen-Fish"notifications@github.com; 发送时间: 2019年5月10日(星期五) 晚上6:19 收件人: "ruotianluo/pytorch-faster-rcnn"pytorch-faster-rcnn@noreply.github.com; 抄送: "Ｍvp_FerryMan"810700982@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [ruotianluo/pytorch-faster-rcnn] a soultion toKeyError:'resnet.bn1.num_batches_tracked' (#140) after doing that，i got another problem：KeyError: 'resnet.conv1.weight'，how can i solve it can you post the screenshot of the error？ ok ! you can change the function in lib/nets/network.py ---def load_pretrained_cnn() — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. are you using the resnet for your training? if not i recommmand you to obey the README to complie your code. but if you are using resnet that modification will be alright — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

you can refer this:https://github.com/ruotianluo/pytorch-faster-rcnn/pull/126/files

**Comment by ruotianluo** [comment]
I think it's fixed already.
