### ISSUE TITLE
Meet the error "行 73: time: 未找到命令" When I went to the step Train Ur own model

### ISSUE THREAD

**Issue by Seanlocked** [ruotianluo/pytorch-faster-rcnn#152]
(base) root@dbbf47a976e1:~/pytorch-faster-rcnn# ./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ DATASET=pascal_voc
+ NET=vgg16
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case ${DATASET} in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ STEPSIZE='[50000]'
+ ITERS=70000
+ ANCHORS='[8,16,32]'
+ RATIOS='[0.5,1,2]'
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2019-10-10_10-56-47
+ exec
++ tee -a experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2019-10-10_10-56-47
+ echo Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2019-10-10_10-56-47
Logging output to experiments/logs/vgg16_voc_2007_trainval__vgg16.txt.2019-10-10_10-56-47
+ set +x
+ '[' '!' -f output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_70000.pth.index ']'
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python ./tools/trainval_net.py --weight data/imagenet_weights/vgg16.pth --imdb voc_2007_trainval --imdbval voc_2007_test --iters 70000 --cfg experiments/cfgs/vgg16.yml --net vgg16 --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]' TRAIN.STEPSIZE '[50000]'
./experiments/scripts/train_faster_rcnn.sh: 行 73: time: 未找到命令

**Comment by ruotianluo** [comment]
apt-get install time, or just remove time.

**Comment by Seanlocked** [comment]
> apt-get install time, or just remove time.

It does work!!!!Thank you,dear author!!!
