### ISSUE TITLE
misinterpretation of "from scratch"

### ISSUE THREAD

**Issue by szq0214** [ruotianluo/pytorch-faster-rcnn#17]
Hi @ruotianluo,

I'm a little confused about the concept of "from scratch" in README. I think you still used the pre-trained models as the initial weights. So it is not suitable here with “from scratch” if referring to this paper: https://arxiv.org/abs/1708.01241.

**Comment by ruotianluo** [comment]
You are true. Just I didnt find a better word. I assume people would understand it.
