### ISSUE TITLE
convert_from_tensorflow.py error

### ISSUE THREAD

**Issue by SLTECH** [ruotianluo/pytorch-faster-rcnn#20]
I use the ./data/scripts/fetch_faster_rcnn_models.sh
to download tf-faster-rcnn's voc_2007_trainval+voc_2012_trainval
and run: 
`python tools/convert_from_tensorflow.py --tensorflow_model data/voc_2007_trainval+voc_2012_trainval/res101_faster_rcnn_iter_110000.ckpt
`
which generate error as follow:

```
File "tools/convert_from_tensorflow.py", line 21, in <module>
    for k in var_dict.keys():
RuntimeError: dictionary changed size during iteration
```

I fixed this by change the line
```
for k in var_dict.keys():
    if 'Momentum' in k:
        del var_dict[k]
```

to 
```
for k in list(var_dict.keys()):
    if 'Momentum' in k:
        del var_dict[k]
```

and 
```
for k in var_dict.keys():
    if k.find('/') >= 0:
        var_dict['resnet' + k[k.find('/'):]] = var_dict[k]
        del var_dict[k]
```

to 
```
for k in list(var_dict.keys()):
    if k.find('/') >= 0:
        var_dict['resnet' + k[k.find('/'):]] = var_dict[k]
        del var_dict[k]
```

seemed ok now.

**Comment by SLTECH** [comment]
After some test, I'm quite sure that all the del var_dict[k] code should be modified to list version.For if I only modify the two lines of code as preview comment, when I run the demo.py, it told me there's some initialization error. After I modified all the " for k in var_dict.key()" to "for k in list(var_dict.key())", the problem dissapeared.
I'm using python3.5+ virtualenv on ubuntu16.04

**Comment by ruotianluo** [comment]
Sorry for not replying. This is py2 py3 incompatibility. I used python2 mostly. You can potentially submit a PR if you want.

**Comment by MichaelLiang12** [comment]
Thank you, it solved my problem. @SLTECH
