### ISSUE TITLE
More than batch size 1

### ISSUE THREAD

**Issue by ruotianluo** [ruotianluo/pytorch-faster-rcnn#21]
@brisker it's better to open a new issue.

In principle, the roi pooling and crop_and_resize are easy to extended to larger batch_size scenario. However, I don't know if other parts are built assuming batch_size one. (The original tf-faster-rcnn totally remove batch_size option and assuming batch_size 1.)

**Comment by DeanChan** [comment]
Possible workaround is to set `iter_size: N` where `N` is the batch size. (https://github.com/rbgirshick/py-faster-rcnn/issues/51)

And to implement it in Pytorch: https://discuss.pytorch.org/t/how-to-implement-accumulated-gradient/3822/13

And I was wondering if there would be a way to run several iteration simultaneously... 0.0 like... via some multiprocessing wrapper or some sort... 😳

**Comment by ruotianluo** [comment]
You check Jianwei’s repository faster-rcnn.pytorch
