### ISSUE TITLE
Could this repo be applied to train own data?

### ISSUE THREAD

**Issue by LouieYang** [ruotianluo/pytorch-faster-rcnn#22]
Could this repo be applied to train own data except for COCO, VOC? Is it OK that I have a dataset with binary classes? It is appreciated if there is more guidance.

**Comment by ruotianluo** [comment]
I guess you have to build your dataloader for your dataset. I actually port it from other repository so I never changed the dataloading part,

**Comment by LouieYang** [comment]
Thanks for quick reply. I will try.
