### ISSUE TITLE
error in  resnet google drive file

### ISSUE THREAD

**Issue by masoudpz** [ruotianluo/pytorch-faster-rcnn#24]
Hi
I downloaded resnet101 weights from google drive (res101_faster_rcnn_iter_1190000.pth)
when i run demo.py i see ioerror as 
res101_faster_rcnn_iter_110000.pth not found
how can i download this file?
when i change 1190000.pth to 110000.pth i see error about tensor sizes.
thanks alot

**Comment by ruotianluo** [comment]
demo uses Voc models.

**Comment by masoudpz** [comment]
@ruotianluo 
thanks for your response,
where can i find Voc models and weights?

**Comment by ruotianluo** [comment]
Sorry, I thought I put it in the google drive. It's now it it.
