### ISSUE TITLE
Memory usage when train a model

### ISSUE THREAD

**Issue by sshaoshuai** [ruotianluo/pytorch-faster-rcnn#29]
Hi,
Do you know how to calculate the maximum GPU memory usage when train a model? So that I can change the SCALE size of input image.
Actually I found that when I trained the model with the original tensorflow version, the SCALE of input image could be larger than this pytorch version. (When training with a big SCALE(about 800 * 1000), pytorch version will be out of memory)

Thanks very much!

**Comment by ruotianluo** [comment]
In my case, 11GB is enough to train resnet on coco.
If you are using latest pytorch, you can use THCUNN grid_sample which could save some memory. (You can do it by set cuddn.enable to False before running grid_sample). I can't see any other simple memory optimization.

**Comment by sshaoshuai** [comment]
Thanks very much for your reply!

That's it.
Maybe the result of out of memory is just caused by grid_sample as following:
![image](https://user-images.githubusercontent.com/8805870/32212165-b35aac5c-be50-11e7-8dc0-3bc6541e1e50.png)

So could you give me more details about how to use a better one?

**Comment by ruotianluo** [comment]
```
    if max_pool:
      pre_pool_size = cfg.POOLING_SIZE * 2
      grid = F.affine_grid(theta, torch.Size((rois.size(0), 1, pre_pool_size, pre_pool_size)))
      torch.backends.cudnn.enabled = False
      crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
      torch.backends.cudnn.enabled = True
      crops = F.max_pool2d(crops, 2, 2)
    else:
      grid = F.affine_grid(theta, torch.Size((rois.size(0), 1, cfg.POOLING_SIZE, cfg.POOLING_SIZE)))
      torch.backends.cudnn.enabled = False
      crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
      torch.backends.cudnn.enabled = True
    return crops
```

**Comment by sshaoshuai** [comment]
It doesn't seem to work for me...
My pytorch version is 0.2.0_4 (installed by conda), is it enough to use this feature?
￼
![1509467678905](https://user-images.githubusercontent.com/8805870/32236195-7bcfbf7e-be9c-11e7-8c9b-311c1cacce73.jpg)

By the way, I choose to use RoiPooling instead of crop_pool_layer, then the GPU memory will not run out of memory. And the vgg16 version runs successfully, but when I train a model with res101, it will cause a error in the training process (such as the 57th iteration): 
**command terminated by signal 11**. no other prompt
Do you have any idea about this error?

Thanks!

**Comment by ruotianluo** [comment]
No, the release version is out-dated.

No, I have no idea. Sounds like there's some memory issue in roipool. However I copy it from yolo2-pytorch repository. I'm not sure where the problem is.

**Comment by sshaoshuai** [comment]
I installed pytorch from source, but still out of memory.
So I reduce the training batchsize and it works.

Anyway, thanks very much!
And, is it easy to modify it to train with multi-gpu?

**Comment by ruotianluo** [comment]
it's now fix batch size to 1 as in tf-faster-rcnn, so it's not that easy.

**Comment by jacktkk** [comment]
@sshaoshuai
hi~I meet the same problem with u.(the error is completely same)
Can u please tell me which codes I should change ?
thanks for u reply!

**Comment by sshaoshuai** [comment]
I just decrease the TRAIN.BATCH_SIZE to 64...

**Comment by jacktkk** [comment]
okay, that works~
thanks a lot!

**Comment by LiangSiyuan21** [comment]
hi~I meet the same problem with u.can you tell me WHERE is TRAIN.BATCH_SIZE.please T T.

**Comment by siddancha** [comment]
Suggestion - upgrade to PyTorch v0.3. It's much more memory efficient.
