### ISSUE TITLE
error when building NMS

### ISSUE THREAD

**Issue by jxchen01** [ruotianluo/pytorch-faster-rcnn#3]
I am using GTX 1080 Ti (sm_61), Python 3.6, ubuntu 16.04

nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_61
cd ../../
python build.py

I keep getting the following messages. Any suggestion on how to fix the issues?

building '_nms' extension
creating home
creating home/jianxuc
creating home/jianxuc/Projects
creating home/jianxuc/Projects/my_project
creating home/jianxuc/Projects/my_project/pytorch-faster-rcnn
creating home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib
creating home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms
creating home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/jianxuc/anaconda3/include/python3.6m -c _nms.c -o ./_nms.o
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/jianxuc/anaconda3/include/python3.6m -c /home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.c -o ./home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.o
In file included from /home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:4:0,
                 from /home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.c:1:
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.c: In function ‘cpu_nms’:
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.c:7:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(boxes), 2, "boxes must be contiguous");
                                          ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:78:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:116:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:115:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.c:9:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(areas), 4, "areas must be contiguous");
                                          ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:78:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:116:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:115:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/jianxuc/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/jianxuc/anaconda3/include/python3.6m -c /home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c -o ./home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.o
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c: In function ‘gpu_nms’:
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:29:35: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* mask_flat = THCudaLongTensor_data(state, mask);
                                   ^
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:37:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long * mask_cpu_flat = THLongTensor_data(mask_cpu);
                                        ^
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:40:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* remv_cpu_flat = THLongTensor_data(remv_cpu);
                                       ^
/home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:23:7: warning: unused variable ‘boxes_dim’ [-Wunused-variable]
   int boxes_dim = THCudaTensor_size(state, boxes, 1);
       ^
gcc -pthread -shared -L/home/jianxuc/anaconda3/lib -Wl,-rpath=/home/jianxuc/anaconda3/lib,--no-as-needed ./_nms.o ./home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms.o ./home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/nms_cuda.o /home/jianxuc/Projects/my_project/pytorch-faster-rcnn/lib/nms/src/cuda/nms_kernel.cu.o -L/home/jianxuc/anaconda3/lib -lpython3.6m -o ./_nms.so

**Comment by ruotianluo** [comment]
There's no error here. They are all warnings, you can just ignore them.

**Comment by jxchen01** [comment]
Thanks!
