### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by wjc852456** [ruotianluo/pytorch-faster-rcnn#31]
When I followed step 2.Train in Train your own model, I used command ./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc res50 and an error occurred:
File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 54, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS
Command exited with non-zero status 1

Anybody knows how to solve this?

**Comment by ruotianluo** [comment]
This sounds like torch installation problem.

**Comment by ruotianluo** [comment]
what version of torch are you using?

**Comment by ruotianluo** [comment]
```
    if max_pool:
      pre_pool_size = cfg.POOLING_SIZE * 2
      grid = F.affine_grid(theta, torch.Size((rois.size(0), 1, pre_pool_size, pre_pool_size)))
      torch.backends.cudnn.enabled = False
      crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
      torch.backends.cudnn.enabled = True
      crops = F.max_pool2d(crops, 2, 2)
    else:
      grid = F.affine_grid(theta, torch.Size((rois.size(0), 1, cfg.POOLING_SIZE, cfg.POOLING_SIZE)))
      torch.backends.cudnn.enabled = False
      crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
      torch.backends.cudnn.enabled = True
    return crops
```

**Comment by robindume** [comment]
I am using torch (0.2.0.post3), and I have same problem.

**Comment by closerbibi** [comment]
seems like the similar issue with the following:
https://github.com/tensorflow/models/issues/523

Just "import torch" above every others module works for me

**Comment by jason718** [comment]
@closerbibi "import torch" above all also works for me
