### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by yoniker** [ruotianluo/pytorch-faster-rcnn#32]
Hi!

So when I'm running demo.py on some images, it seems that the net object takes increasing amounts of space.

Specifically asizeof(net) (from pympler.sizeof) shows that the net object takes just over 1GB after loading dict state,
after detection on the first picture it takes about 5GB, after the third about 6.7GB, after that it stopts changing in size for 5-6 pictures, then takes 7.7GB, then back to 6.7GB, after that there's "out of memory" error. A really weird pattern!

I'm trying the default resnet 101 with all the defaults from demo.py.
My GPU is Nvidia GTX1080.

How can I fix this issue?

**Comment by ruotianluo** [comment]
Can you show me the stack traces of the error?

**Comment by yoniker** [comment]
Alright.

I've modified demo.py a bit so that demo() now returns the number of people it found.
If you want to take a look at that code let me know.


Here's nvidia-smi output while the program is still running:


+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      5384      G   /usr/lib/xorg/Xorg                           151MiB |
|    0      5922      G   compiz                                        79MiB |
|    0      8631      C   ccminer/algocrypto                           125MiB |
|    0     11606      C   python                                      6982MiB |
|    0     31146      G   /usr/lib/xorg/Xorg                            43MiB |
+-----------------------------------------------------------------------------+

And that's python's output (I am not too sure if that's what you meant when you wrote stack trace, let me know if you need anything else):

Detection took 0.266s for 219 object proposals
overall people found: 1 and faces found : 0
Detections for the picture 100930062.1.jpg
after boxes
Detection took 0.185s for 96 object proposals
overall people found: 1 and faces found : 0
Detections for the picture 159358710.1.jpg
after boxes
Detection took 0.223s for 142 object proposals
overall people found: 1 and faces found : 0
Detections for the picture 120599771.1.jpg
after boxes
Detection took 0.333s for 291 object proposals
overall people found: 1 and faces found : 0
Detections for the picture 68545810.4.jpg
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 170, in <module>
  File "<string>", line 98, in demo
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/model/test.py", line 95, in im_detect
    _, scores, bbox_pred, rois = net.test_image(blobs['data'], blobs['im_info'])
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 430, in test_image
    self.forward(image, im_info, None, mode='TEST')
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 394, in forward
    rois, cls_prob, bbox_pred = self._predict()
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 368, in _predict
    pool5 = self._crop_pool_layer(net_conv, rois)
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 218, in _crop_pool_layer
    return Network._crop_pool_layer(self, bottom, rois, cfg.RESNET.MAX_POOL)
  File "/home/cv2cuda/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 129, in _crop_pool_layer
    crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
  File "/home/cv2cuda/.virtualenvs/cv/local/lib/python3.5/site-packages/torch/nn/functional.py", line 995, in grid_sample
    return GridSampler.apply(input, grid)
  File "/home/cv2cuda/.virtualenvs/cv/local/lib/python3.5/site-packages/torch/nn/_functions/vision.py", line 27, in forward
    input = input.contiguous()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66

**Comment by ruotianluo** [comment]
It's not leaked, it's just out of memory I guess. because grid sample is memory costly. Should be better now. (Although the response seems too late.)
