### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by ankur6ue** [ruotianluo/pytorch-faster-rcnn#36]
Has anyone tried this on windows? I'm in the process of trying to get it to work, but wanted to see if anyone has already tried and has any suggestions.

**Comment by nick-jia** [comment]
Based on my experience, to use this on windows, two files in pytorch-faster-rcnn\lib\layer_utils\csrc\cuda need to be slightly modified. For details, please see [https://github.com/facebookresearch/maskrcnn-benchmark/pull/409](url).
