### ISSUE TITLE
The difference of roi_pooling and  crop_roi_pooling

### ISSUE THREAD

**Issue by xpain1** [ruotianluo/pytorch-faster-rcnn#39]
when i read your code, i find a layer named crop roi pooling that i never heard before,so  could you tell the difference of roi_pooling and crop roi_pooling ,or give me some datum about them.thx

**Comment by ruotianluo** [comment]
I guess you are saying crop_and_resize??? That's basically roi_align. The name is inherited from tf-faster-rcnn

**Comment by xpain1** [comment]
what you mean is that  the crop_roi_pooling is roi_align in mask rcnn?

**Comment by ruotianluo** [comment]
Yes.

**Comment by xpain1** [comment]
i see  ,thanks
