### ISSUE TITLE
Question Regarding def _crop_pool_layer(self, bottom, rois, max_pool=True)

### ISSUE THREAD

**Issue by ankur6ue** [ruotianluo/pytorch-faster-rcnn#41]
While computing the "theta" for the affine transformation, shouldn't the boundary of the box be:

top left corner: (x1-width)/width, (y1-height)/height
bottom right corner: (x2+1)/width, (y2+1)/height
? 

That way if x1,y1=0 and x2,y2= width-1, height-1, the box maps to -1,-1,  1,1
as needed by the affine transformation functions in pytorch?

**Comment by ruotianluo** [comment]
Can you write a snippet to prove your statement. I don't have much time to derive it again because of the conference deadline. I think I did it carefully.
thanks.

**Comment by ankur6ue** [comment]
Your theta is correct. I was not understanding how the affine transformation parameters were computed correctly. I have attached a document showing how the affine transformation matrix that you use comes about. Others may also find this useful..
[affine_transformation_proof.pdf](https://github.com/ruotianluo/pytorch-faster-rcnn/files/1477404/affine_transformation_proof.pdf)

**Comment by drcege** [comment]
@ankur6ue  Could you please upload a clearer one?  I cannot recognize the sentences you wrote.

**Comment by ankur6ue** [comment]
I have written a blog post describing how R-CNN's work (including how the affine transformation matrix is generated) in detail:
http://www.telesens.co/2018/03/11/object-detection-and-classification-using-r-cnns/
