### ISSUE TITLE
about the data order of roi_pooling (cpu version)

### ISSUE THREAD

**Issue by hux999** [ruotianluo/pytorch-faster-rcnn#43]
I have read the code in "lib/layer_utils/roi_pooling/src/roi_pooling.c" which is the cpu version of roi_pooling. I found that the data order follow the NHWC format when indexing bottom data, but pytorch follow the NCHW format. it is my mistake or something else?

**Comment by ruotianluo** [comment]
I actually never tried cpu version. It should be trivial to test. I'm busy recently; I would appreciate if you can test it.

**Comment by hux999** [comment]
you can check the lines 22~27
    // data height
    int data_height = THFloatTensor_size(features, 1); // it could be THFloatTensor_size(features, 2);
    // data width
    int data_width = THFloatTensor_size(features, 2); // it could be THFloatTensor_size(features, 3);
    // Number of channels
    int num_channels = THFloatTensor_size(features, 3); // it could be THFloatTensor_size(features, 1);
and line 87
const int index = (h * data_width + w) * num_channels + c; // it could be (c*data_height+h)*data_width + w
thanks for your great job

**Comment by ruotianluo** [comment]
I actually didin't write these part. It's ported form other repository,

**Comment by hux999** [comment]
it is my mistake. The order of feature have been changed in  line 23 of "lib/layer_utils/roi_pooling/roi_pooling.py" : 
_features = features.permute(0, 2, 3, 1)
