### ISSUE TITLE
bbox_inside_weights/outside_weights

### ISSUE THREAD

**Issue by ankur6ue** [ruotianluo/pytorch-faster-rcnn#45]
What is the significance of bbox_inside and outside weights in smooth_l1_loss? I followed the fast and faster R-CNN papers closely and not seeing them being defined anywhere?

**Comment by ruotianluo** [comment]
https://github.com/rbgirshick/py-faster-rcnn/blob/96dc9f1dea3087474d6da5a98879072901ee9bf9/lib/fast_rcnn/config.py#L84

**Comment by ruotianluo** [comment]
It's deprecated.

**Comment by ankur6ue** [comment]
got it, thanks. closing issue
