### ISSUE TITLE
tools/demo.py

### ISSUE THREAD

**Issue by jacktkk** [ruotianluo/pytorch-faster-rcnn#47]
Sorry for bothering u!
When I run the demo.py, I wish to see all the detection results on the one image(if I test a image.I wish it return only one image with all detected things.) but I don't know how to change the function....
thx for your reply.

**Comment by ruotianluo** [comment]
you can try to change the vis_detections function.

**Comment by jacktkk** [comment]
ok, thx~

**Comment by mseals1** [comment]
@jacktkk I have included a script that does this. It's under tools/demo_all_bboxes.py Hopefully it works for you!
