### ISSUE TITLE
is "res101_faster_rcnn_iter_110000.pth" provided?

### ISSUE THREAD

**Issue by hengck23** [ruotianluo/pytorch-faster-rcnn#5]
I am trying to run the evaluation code :./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101.
 
It seems that ./data/scripts/fetch_faster_rcnn_models.sh gives me the tensorflow model "res101_faster_rcnn_iter_110000.ckpt.data-00000-of-00001/index/meta/ ... etc"

where can i find the pytorch model?

**Comment by ruotianluo** [comment]
Sorry for the unclear instruction, can you follow the rest lines of that section.  (the fetch script is commented if you pay attention.

**Comment by hengck23** [comment]
i found the files at the goggle drive. thanks!
