### ISSUE TITLE
crop vs roi pool

### ISSUE THREAD

**Issue by shanyuhu** [ruotianluo/pytorch-faster-rcnn#51]
@ruotianluo , I tried to train the network with crop layer and roi pool layer separately, but the results of using roi pool layer is far worse than the crop one. Have you got this problem?

**Comment by ruotianluo** [comment]
The result wasn't far worse for me. But it's true that crop is better. It's possible that I broke the roi pool code during some changes I made because I haven't tested roi pool for a while.

**Comment by shanyuhu** [comment]
Will you check and test the roi pool part ? I am also trying to figure it out.

**Comment by shanyuhu** [comment]
@ruotianluo , the roi pool works well, and can get comparable performance with crop layer. I previously made a tiny mistake.
