### ISSUE TITLE
Stride for layer4 in resnet

### ISSUE THREAD

**Issue by ruotianluo** [ruotianluo/pytorch-faster-rcnn#6]
@philokey, I will create a new branch for this so that the current pretrained won't be messed up.

This issue was originally opened in https://github.com/ruotianluo/pytorch-resnet/issues/2

**Comment by ruotianluo** [comment]
You can check the convert_from_tensorflow branch now.

**Comment by philokey** [comment]
Thanks, I will try it.

**Comment by ruotianluo** [comment]
It's now significantly slower (because the stride 1 needs more computation) than tf-faster-rcnn, I will investigate what's the bottleneck.

**Comment by Feynman27** [comment]
@ruotianluo I'm trying to train a resnet101+faster rcnn model starting from image net weights. Changine the stride in layer4 from 2->1 does indeed increase the training time. Did you ever resolve the bottleneck?

**Comment by ruotianluo** [comment]
@Feynman27 I haven't profiled the code in detail. But it should be faster after commit https://github.com/ruotianluo/pytorch-faster-rcnn/commit/df3cc0590cd077cab4b81503673d498a18bded88
