### ISSUE TITLE
demo.py results

### ISSUE THREAD

**Issue by mseals1** [ruotianluo/pytorch-faster-rcnn#60]
Does tools/demo.py output any results? I wasn't able to find any after running demo.py. So, if it doesn't, which part of the code should I add a plt.savefig() to for it to output the full result of each image?

I added plt.savefig() after the demo() cal in the for at the bottom of the script, but it seems to be only saving one of the results (ex. person) instead of all of the bboxes (ex. person, horse, dog, etc).

**Comment by ruotianluo** [comment]
Try demo.ipynb?

I'm not sure how savefig works. Maybe you need to save after each plt.draw()?

**Comment by mseals1** [comment]
Thanks for the extremely quick reply. And okay, I'll try both of those suggestions. I'm running the code on AWS, so I'll figure out how to get Jupyter working on there and see if I'm able to view the results in a browser.

Below is one of the results I'm getting when saving it in the for loop after demo is called.
![demo004545](https://user-images.githubusercontent.com/8727560/35124569-8dfd64b0-fc74-11e7-826a-900ed94c4d61.jpg)

I'll move the savefig call after plt.draw() to see how that affects the output.

**Comment by mseals1** [comment]
Is there a way to get all detections in one image?

**Comment by ruotianluo** [comment]
you can, but you need to modify the code.
