### ISSUE TITLE
GridSampler needs CuDNN for processing CUDA inputs, but CuDNN is not enabled

### ISSUE THREAD

**Issue by tuzixini1** [ruotianluo/pytorch-faster-rcnn#65]
When I try this code with command 

`GPU_ID=0
CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py --dataset='pascal_voc'`

Then I get the Error:

`raise RuntimeError("GridSampler needs CuDNN for processing CUDA inputs,"
RuntimeError: GridSampler needs CuDNN for processing CUDA inputs, but CuDNN is not enabled
`

I have check the computer and sure there is CUDA and CuDNN installed

` Python 2.7.13 |Anaconda custom (64-bit)| (default, Sep 22 2017, 00:47:24)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> import torch
> print torch.backends.cudnn.version()
6021`

Try to Google a lot but can not find out where the problem is.
Can anyone help me ? Thanks!

**Comment by ruotianluo** [comment]
Are you using pytorch 0.2?

**Comment by tuzixini1** [comment]
@ruotianluo Yes, I am using PyTorch 0.2 with Python 2.7.13

**Comment by ruotianluo** [comment]
Upgrade to 0.3

**Comment by tuzixini1** [comment]
@ruotianluo ok,I will have a try, thank you

**Comment by tuzixini1** [comment]
@ruotianluo Problem solved, Thank you.
