### ISSUE TITLE
CudNN error although cuddnn is enabled

### ISSUE THREAD

**Issue by akumar14** [ruotianluo/pytorch-faster-rcnn#67]
File "/scratch0/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 125, in _crop_pool_layer
    crops = F.grid_sample(bottom.expand(rois.size(0), bottom.size(1), bottom.size(2), bottom.size(3)), grid)
  File "/scratch0/anaconda/lib/python2.7/site-packages/torch/nn/functional.py", line 995, in grid_sample
    return GridSampler.apply(input, grid)
  File "/scratch0/anaconda/lib/python2.7/site-packages/torch/nn/_functions/vision.py", line 23, in forward
    GridSampler._enforce_cudnn(input)
  File "/scratch0/anaconda/lib/python2.7/site-packages/torch/nn/_functions/vision.py", line 14, in _enforce_cudnn
    raise RuntimeError("GridSampler needs CuDNN for processing CUDA inputs,"
**RuntimeError: GridSampler needs CuDNN for processing CUDA inputs, but CuDNN is not enabled**
29.02user 12.43system 1:41.33elapsed 40%CPU (0avgtext+0avgdata 1734208maxresident)k
264inputs+72outputs (1major+587382minor)pagefaults 0swaps

-------- 
I have 2 Titan X and cuda 8 is enabled. This error appears after dataset loading and roidb loading and imagenet wegiht loading is done.

Any insights what might be causing this error.

**Comment by ruotianluo** [comment]
You are probably using pytorch 0.2. Pytorch 0.3 has non cudnn grid sample which is more memory efficient, so I manually disable it.

**Comment by akumar14** [comment]
Any idea how to install Pytorch 0.3 with anaconda. 
I used the following again just now: conda install pytorch torchvision -c pytorch 
and ran the training script. It still throws the same error

**Comment by ruotianluo** [comment]
Try to make sure that you don't have other pytorch installed.

do things like:
pip uninstall pytorch
conda uninstall pytorch.

Make sure they are totally removed then install again.

**Comment by akumar14** [comment]
Worked !!
Apparently conda was unable to find pytorch 0.3 . I had to install it using pip. 

Thanks !!
