### ISSUE TITLE
a little issue

### ISSUE THREAD

**Issue by jacktkk** [ruotianluo/pytorch-faster-rcnn#69]
Sorry for bothering u !
I wonder why u thought the new network will better than the order one?
Is model enhancement specific to some particular objects or universal?
Thx for your reply~

**Comment by ruotianluo** [comment]
It seems perform better which I'm not sure why. I did this mainly because I want to convert the tensorflow pretrained model so that I don't need to train it.

**Comment by jacktkk** [comment]
Thank you for your prompt reply
Before I train the model, I want to confirm another thing: you said "training details have been changed" 
is that mean [https://github.com/ruotianluo/pytorch-faster-rcnn/commit/44c07f022233461effb7341306fb1eaf891e96c8](url)

**Comment by jacktkk** [comment]
I'm very thanks that you help me .
