### ISSUE TITLE
Did you check the nms_gpu? 

### ISSUE THREAD

**Issue by mks0601** [ruotianluo/pytorch-faster-rcnn#73]
Hi, did you check the nms_gpu?
I used your nms_gpu to my implementation, however it did not remove overlapped boxes well.
In the nms/src/cuda/nms_kernel.cu, there is no o(n^2) loop, only o(n) loop exist, which means current box does not change. Also, 't' variable is long long int variable (can contain single value), however when inspecting IoU with cur box and other boxes, 't' just contain single value so that it does not provide any information for each overlapped box.

**Comment by ruotianluo** [comment]
This kernel is ported from https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/nms/nms_kernel.cu

I would think it's correct.

About t, t has 64 bits, so it can contains at most 64 bool values.
