### ISSUE TITLE
problems about BATCH_SIZE

### ISSUE THREAD

**Issue by Destinyzs** [ruotianluo/pytorch-faster-rcnn#74]
`IMS_PER_BATCH` is default 1,this means one image per batch.But what's the meaning of the `BATCH_SIZE`?
Comments say `Minibatch size (number of regions of interest [ROIs])`. 
But i am still confused.

**Comment by ruotianluo** [comment]
eh.... it's indeed number of rois....... For each image, you need to choose BATCH_SIZE ROIs, to train the detection head.

**Comment by Destinyzs** [comment]
But, in the `minibatch.py`,some code exists like this:
```
  assert(cfg.TRAIN.BATCH_SIZE % num_images == 0), \
    'num_images ({}) must divide BATCH_SIZE ({})'. \
    format(num_images, cfg.TRAIN.BATCH_SIZE)
```
Does this means we have to firstly chose `BATCH_SIZE` images into the memory,and then for training, one image per step?

**Comment by ruotianluo** [comment]
No. For each images you have BATCH_SIZE rois.

**Comment by ruotianluo** [comment]
So, in fact batch_size is the rois for all images. Since we are always using num_images=1, so no bother.

**Comment by Destinyzs** [comment]
Oh,if so,i get it! Thanks!
