### ISSUE TITLE
Error when running demo.py: No module named '_ext'

### ISSUE THREAD

**Issue by lwoiceshyn** [ruotianluo/pytorch-faster-rcnn#8]
Can you explain what this import is doing in path_nms.py?
from _ext import nms
It's preventing me from running the demo script.  I'm using Python 3.6.

**Comment by ruotianluo** [comment]
Did you follow the fourth step of https://github.com/ruotianluo/pytorch-faster-rcnn#installation ?

**Comment by lwoiceshyn** [comment]
Yes, it seems to run fine, here is the output:

`Including CUDA code.
/home/leow/pytorch-faster-rcnn/lib/nms
generating /tmp/tmpyk65xa34/_nms.c
running build_ext
building '_nms' extension
creating home
creating home/leow
creating home/leow/pytorch-faster-rcnn
creating home/leow/pytorch-faster-rcnn/lib
creating home/leow/pytorch-faster-rcnn/lib/nms
creating home/leow/pytorch-faster-rcnn/lib/nms/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/leow/anaconda3/include/python3.6m -c _nms.c -o ./_nms.o
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/leow/anaconda3/include/python3.6m -c /home/leow/pytorch-faster-rcnn/lib/nms/src/nms.c -o ./home/leow/pytorch-faster-rcnn/lib/nms/src/nms.o
In file included from /home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:4:0,
                 from /home/leow/pytorch-faster-rcnn/lib/nms/src/nms.c:1:
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms.c: In function ‘cpu_nms’:
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms.c:7:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(boxes), 2, "boxes must be contiguous");
                                          ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:78:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:116:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:115:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms.c:9:42: warning: passing argument 1 of ‘THLongTensor_isContiguous’ from incompatible pointer type [-Wincompatible-pointer-types]
     THArgCheck(THLongTensor_isContiguous(areas), 4, "areas must be contiguous");
                                          ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:78:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:39: note: expected ‘const THLongTensor * {aka const struct THLongTensor *}’ but argument is of type ‘THFloatTensor * {aka struct THFloatTensor *}’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                                       ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:116:37: note: in definition of macro ‘TH_CONCAT_4_EXPAND’
 #define TH_CONCAT_4_EXPAND(x,y,z,w) x ## y ## z ## w
                                     ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THTensor.h:8:27: note: in expansion of macro ‘TH_CONCAT_4’
 #define THTensor_(NAME)   TH_CONCAT_4(TH,Real,Tensor_,NAME)
                           ^
/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:115:12: note: in expansion of macro ‘THTensor_’
 TH_API int THTensor_(isContiguous)(const THTensor *self);
            ^
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/leow/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/leow/anaconda3/include/python3.6m -c /home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c -o ./home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.o
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c: In function ‘gpu_nms’:
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:29:35: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* mask_flat = THCudaLongTensor_data(state, mask);
                                   ^
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:37:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long * mask_cpu_flat = THLongTensor_data(mask_cpu);
                                        ^
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:40:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   unsigned long long* remv_cpu_flat = THLongTensor_data(remv_cpu);
                                       ^
/home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.c:23:7: warning: unused variable ‘boxes_dim’ [-Wunused-variable]
   int boxes_dim = THCudaTensor_size(state, boxes, 1);
       ^
gcc -pthread -shared -L/home/leow/anaconda3/lib -Wl,-rpath=/home/leow/anaconda3/lib,--no-as-needed ./_nms.o ./home/leow/pytorch-faster-rcnn/lib/nms/src/nms.o ./home/leow/pytorch-faster-rcnn/lib/nms/src/nms_cuda.o /home/leow/pytorch-faster-rcnn/lib/nms/src/cuda/nms_kernel.cu.o -L/home/leow/anaconda3/lib -lpython3.6m -o ./_nms.so`

**Comment by ruotianluo** [comment]
I guess it's because I'm running under python 2.7.

Try:
`from ._ext import nms`

**Comment by lwoiceshyn** [comment]
Yes, the directory imports are different in 3.6. That fix worked for the issue.
