### ISSUE TITLE
Can I compile the lib without GPU?

### ISSUE THREAD

**Issue by adamzjk** [ruotianluo/pytorch-faster-rcnn#80]
Hi i'm using macbook without CUDA supported GPU which means I cannot have cuda installed on my local computer...

but i saw your source code have both `crop_and_resize.c` and `crop_and_resize_gpu.c` files so I guess I can run it on CPU right?

so can I compile the lib without cuda?

**Comment by ruotianluo** [comment]
You should be able to comment out the compilation of the cuda part. However I'm assuming cuda every where in my code.  You need also to modify that to run on CPU.

**Comment by adamzjk** [comment]
Thanks, I run the training part on GPU severs but I need to do some testing on my laptop. 

I've done some google search and managed to install CUDA without GPU on my MacBook and it seems everything work out well.
