### ISSUE TITLE
AssertionError in training the model

### ISSUE THREAD

**Issue by cxxszz** [ruotianluo/pytorch-faster-rcnn#86]
I set up the VGG16 model as the readme file and moved the .pth file to the right folder.
After I run `./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16` in the root file. I have an assertion error:

Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/lwj/pytorch-faster-rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
10022 roidb entries
Output will be saved to `/home/lwj/pytorch-faster-rcnn/output/vgg16/voc_2007_trainval/default`
TensorFlow summaries will be saved to `/home/lwj/pytorch-faster-rcnn/tensorboard/vgg16/voc_2007_trainval/default`
Loaded dataset `voc_2007_test` for training
Set proposal method: gt
Preparing training data...
voc_2007_test gt roidb loaded from /home/lwj/pytorch-faster-rcnn/data/cache/voc_2007_test_gt_roidb.pkl
done
4952 validation roidb entries
Filtered 0 roidb entries: 10022 -> 10022
Filtered 0 roidb entries: 4952 -> 4952
Solving...
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/lwj/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/lwj/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 220, in train_model
    lsf, nfiles, sfiles = self.find_previous()
  File "/home/lwj/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 157, in find_previous
    assert len(nfiles) == lsf
AssertionError
Command exited with non-zero status 1
11.94user 1.51system 0:11.96elapsed 112%CPU (0avgtext+0avgdata 769504maxresident)k
0inputs+16outputs (0major+200311minor)pagefaults 0swaps

What caused this?

**Comment by weitt** [comment]
I meet the same problem.how do you solve it ?

**Comment by RiccardoGrigoletto** [comment]
Same

**Comment by minji-o-j** [comment]
I think you have to move the ,pkl and .pth file in the same path
I solve it like that
