### ISSUE TITLE
140 iters then the loss be NAN

### ISSUE THREAD

**Issue by CoderHHX** [ruotianluo/pytorch-faster-rcnn#87]
iter: 100 / 70000, total loss: 1.238060
 >>> rpn_loss_cls: 0.503647
 >>> rpn_loss_box: 0.560238
 >>> loss_cls: 0.128045
 >>> loss_box: 0.046130
 >>> lr: 0.001000
speed: 0.645s / iter
iter: 120 / 70000, total loss: 1.312589
 >>> rpn_loss_cls: 0.471951
 >>> rpn_loss_box: 0.668822
 >>> loss_cls: 0.135918
 >>> loss_box: 0.035899
 >>> lr: 0.001000
speed: 0.626s / iter
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 379, in train_net
    sw.train_model(max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 267, in train_model
    self.net.train_step(blobs, self.optimizer)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 447, in train_step
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'])
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 396, in forward
    self._add_losses() # compute losses
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 198, in _add_losses
    assert (rpn_bbox_pred==rpn_bbox_pred).all()
AssertionError

I use this PyTorch faster-rcnn to train the VisDrone data. I transform the format into pascal_voc and change the dataload. At the same time,I clean up the Cache files and make sure the ground truth boxes in roidb files have the value >0 and <width or height. However, when I train my data. It will be NAN after 140 iters. I have run the demo and original dataset both VOC and COCO and achieve same performance as ruotianluo's  @ruotianluo  in readme. So what's the problems of my model. Thanks!

**Comment by ruotianluo** [comment]
Are you able to train on VOC or coco correctly?

**Comment by CoderHHX** [comment]
Yes, I can train on VOC and COCO correctly and achieve the same performance as your readme say

**Comment by CoderHHX** [comment]
Finally, I solve the problem that in my dataset, the start of x and y is 0, so the code that make the base to be 0 is not work for me.

**Comment by Karthik-Suresh93** [comment]
@CoderHHX 
Could you please clarify in detail how you solved this problem?

**Comment by CoderHHX** [comment]
@Karthik-Suresh93 
I just make this change in dataload class:
 
bbox = obj.find('bndbox')     #################################################################################
      #For my data VisDrone ,the image pixel start from 0 ,so can not sub 1 when load object bbox, After I change his my code works without NAN in loss_box
      # Make pixel indexes 0-based
      x1 = float(bbox.find('xmin').text) #- 1
      y1 = float(bbox.find('ymin').text) #- 1
      x2 = float(bbox.find('xmax').text) #- 1
      y2 = float(bbox.find('ymax').text) #- 1
