### ISSUE TITLE
Evaluation Error with Annotation Path

### ISSUE THREAD

**Issue by lwoiceshyn** [ruotianluo/pytorch-faster-rcnn#9]
I'm assuming this is just another Python3-induced error, but trying to debug and fix is challenging with such a big project, so any ideas would help a lot.

I'm not sure exactly how it's intended to work, but it seems as though for some reason it saved an empty pickle file called test.txt_annots.pkl in the folder /home/leow/pytorch-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/ (I printed this path out in the output below), and when it tries to load this it errors. 

Any ideas of where this could have went wrong?

`Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
**/home/leow/pytorch-faster-rcnn/data/VOCdevkit2007/VOC2007/ImageSets/Main/test.txt_annots.pkl**
Traceback (most recent call last):
  File "/home/leow/pytorch-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 128, in voc_eval
    recs = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_net.py", line 117, in <module>
    test_net(net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/leow/pytorch-faster-rcnn/tools/../lib/model/test.py", line 194, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/leow/pytorch-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 280, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/leow/pytorch-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 243, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/leow/pytorch-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 130, in voc_eval
    recs = pickle.load(f, encoding='bytes')
EOFError: Ran out of input
`

**Comment by ruotianluo** [comment]
I haven't changed any part of this code. This is identical what's in tf-faster-rcnn. One possibility is you halt the program when pickle is dumping the cachefile so you can't load it next time. Can you delete these cachefiles and run the program again?

**Comment by lwoiceshyn** [comment]
Thanks, that worked.

On a side note:
I got a Mean AP of 0.5520 on VOC2007 using your pretrained res101 model after 110k iterations, does that seem right? Which is the best performing of the pretrained models?

**Comment by ruotianluo** [comment]
There's no randomness during test, so the result should be the same as in README.md. Are you downloading the model trained using crop_and_resize?

**Comment by lwoiceshyn** [comment]
No, I only downloaded the roi_pooling versions.
The name of the file used is 'res101_faster_rcnn_iter_110000.pth'

**Comment by ruotianluo** [comment]
So that's the reason why the result is not correct. If you want to use roi pooling version,
https://github.com/ruotianluo/pytorch-faster-rcnn/blob/master/experiments/cfgs/res101.yml
set the POOLING_MODE to roi_pooling

**Comment by lwoiceshyn** [comment]
Thanks!
